In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Imports

In [2]:
df = pd.read_csv("../data/processed/engineered_features.csv")

df.shape
df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes,subject_portuguese,parent_edu_avg,total_alcohol,has_support
0,18,4,4,2,2,0,4,3,4,1,...,0,0,1,1,0,0,0,4.0,2,1
1,17,1,1,1,2,0,5,3,3,1,...,0,0,0,1,1,0,0,1.0,2,1
2,15,1,1,1,2,3,4,3,2,2,...,1,0,1,1,1,0,0,1.0,5,1
3,15,4,2,1,3,0,3,2,2,1,...,1,1,1,1,1,1,0,3.0,2,1
4,16,3,3,1,2,0,4,3,2,1,...,1,0,1,1,0,0,0,3.0,3,1

# Load Engineering Dataset

In [3]:
df = pd.read_csv("../data/processed/engineered_features.csv")

df.shape
df.head()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes,subject_portuguese,parent_edu_avg,total_alcohol,has_support
0,18,4,4,2,2,0,4,3,4,1,...,0,0,1,1,0,0,0,4.0,2,1
1,17,1,1,1,2,0,5,3,3,1,...,0,0,0,1,1,0,0,1.0,2,1
2,15,1,1,1,2,3,4,3,2,2,...,1,0,1,1,1,0,0,1.0,5,1
3,15,4,2,1,3,0,3,2,2,1,...,1,1,1,1,1,1,0,3.0,2,1
4,16,3,3,1,2,0,4,3,2,1,...,1,0,1,1,0,0,0,3.0,3,1